services:

    _defaults:
        public: false
        autowire: true

    APICodingDays\KonfigQL\:
        resource: 'src/*'
        exclude: 'src/**/DataType'
        public: true

    APICodingDays\KonfigQL\Shared\Service\NamespaceMapper:
        class: APICodingDays\KonfigQL\Shared\Service\NamespaceMapper
        tags: ['graphql_namespace_mapper']
